#!/bin/bash
echo $(id)
if [ ! -f "/home/docker/.config/aria2c/aria2.session" ];then
    mkdir -p ~/.config/aria2c
    touch ~/.config/aria2c/aria2.session
fi

/usr/bin/aria2c --conf-path=/aria2/aria2.conf
