#!/bin/bash

if [ ! -f "/home/docker/.config/aria2c/aria2.session" ];then
    mkdir ~/.config/aria2c
    touch /home/docker/.config/aria2c/aria2.session
fi

/usr/bin/aria2c --conf-path=/aria2/aria2.conf
